
export const VENEZUELAN_BANKS = [
    { value: "banesco", label: "Banesco" },
    { value: "mercantil", label: "Mercantil" },
    { value: "provincial", label: "Provincial" },
    { value: "bdv", label: "Banco de Venezuela" },
    { value: "bnc", label: "Banco Nacional de Crédito (BNC)" },
    { value: "bancaribe", label: "Bancaribe" },
    { value: "exterior", label: "Banco Exterior" },
    { value: "bancamiga", label: "Bancamiga" },
    { value: "tesoro", label: "Banco del Tesoro" },
    { value: "bicentenario", label: "Banco Bicentenario" },
    { value: "banplus", label: "Banplus" },
    { value: "activo", label: "Banco Activo" },
    { value: "sofitasa", label: "Banco Sofitasa" },
    { value: "plaza", label: "Banco Plaza" },
    { value: "delsur", label: "DelSur" },
    { value: "bfc", label: "BFC Banco Fondo Común" },
    { value: "100banco", label: "100% Banco" },
    { value: "bancrecer", label: "Bancrecer" },
    { value: "mibanco", label: "Mi Banco" },
    { value: "bangente", label: "Bangente" },
    { value: "venezolano_credito", label: "Venezolano de Crédito" },
    { value: "agricola", label: "Banco Agrícola de Venezuela" },
    { value: "caroni", label: "Banco Caroní" },
    { value: "otro", label: "Otro" },
];
